version: '2'
services:
    house-datastore:
        container_name: house-datastore
        image: 'mongo:3.6'
        ports:
            - '27017:27017'
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/log/mongo.log
        command: 'mongod'

    house-app:
        container_name: house-app
        image: 'house-app:latest'
        restart: always
        ports:
            - '8000:8000'
        environment:
            - DEBUG_PROPS=${DEBUG_PROPS}
        links:
            - house-datastore
        depends_on:
            - house-datastore

    house-ui:
        container_name: house-ui
        image: 'house-ui:latest'
        restart: always
        ports:
            - '80:81'
        links:
            - house-app
        depends_on:
            - house-app