version: '2'
services:
    datastore:
        container_name: datastore
        image: 'mongo:3.6'
        ports:
            - '27017:27017'
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/log/mongo.log
        command: 'mongod --logpath=/log/mongo.log'

    house-app:
        container_name: house-app
        image: 'pekket-house-app:latest'
        restart: always
        ports:
            - '8080:8080'
        environment:
            - DEBUG_PROPS=${DEBUG_PROPS}
        links:
            - datastore
        depends_on:
            - datastore