# MongoDB settings
spring:
  data:
    mongodb:
      database: data
      port: 27018
      uri: mongodb://house-datastore

#Tomcat settings
server:
  port: 8081

#IFTT webhook settings
iftt:
  webhook:
    event:
      name: "newhouse"
      id: "WEBHOOK_ID"
